language: node_js

env:
   - DATABASE_URL=postgresql://postgres@localhost:5432/movie_app

node_js:
  - 12

before_script:
  - psql -c 'create database movie_app' -U postgres
  - psql -U postgres -d movie_app -a -f ./server/sql/users.sql
  - psql -U postgres -d movie_app -a -f ./server/sql/data.sql
  
services:
  - postgresql

#  script: server/test/test.api.js run test